### ISSUE TITLE
Запретить хранение access_token в конфигурации

### ISSUE THREAD

**Issue by SevereCloud** [VKCOM/vk-miniapps-deploy#1]
### Мотивация

Хранение `access_token` в конфигурационном файле небезопасно.

Группа исследователей из Университета Северной Каролины [провели исследование](https://www.ndss-symposium.org/wp-content/uploads/2019/02/ndss2019_04B-3_Meli_paper.pdf) и установили, что свыше 100 тыс. репозиториев содержат API-ключи, токены и криптографические ключи. [[habr]](https://habr.com/ru/post/444930/)

GitHub и подобные платформы для открытой публикации исходного кода сегодня стали стандартным инструментов разработчиков. Однако возникает проблема, если этот открытый код работает с токенами аутентификации, секретными ключами API и приватными криптографическими ключами. Критичная информация может быть случайно обнародована.

### Бэкграунд 

В данный момент `access_token` задается в конфигурационном файле. Если `access_token` не найден, то приложение предложит авторизоваться, а после сохранит ключ в конфигурационный файл.

### Решение

- получать `access_token` из переменных окружения (`process.env.ACCESS_TOKEN`)
- не читать `access_token` из конфигурации
- не сохранять `access_token` в конфигурацию при авторизации

**Comment by Mobyman** [comment]
Специально из-за мотивации файл был вынесен из основного конфигурационного файла в отдельный, который содержит исключительно приватную информацию - в т.ч., которая указывается в самом начале самим разработчиком (например **секретный** и **сервисный** токен). 

В следующей версии добавлю чтение этой информации из env-переменных, однако считаю, что в большинстве случаев пользователь будет достаточно квалифицирован для того, чтобы не коммитить файл, в котором **он сам** указал чувствительную информацию.

**Comment by SevereCloud** [comment]
> ...исключительно приватную информацию...

`app_id` и `staticpath` удобно хранить в vk-hosting-config.json, для нужд CI.

> в большинстве случаев пользователь будет достаточно квалифицирован для того, чтобы не коммитить файл, в котором он сам указал чувствительную информацию.

**Утечка данных в Uber**

> Двум злоумышленникам удалось получить доступ к закрытой странице Uber на GitHub и воспользоваться полученными в результате этого учетными данными для аутентификации в аккаунте Amazon Web Services

**Утечка данных в DJI** 

> Осенью 2017 года выяснилось, что разработчики производителя квадрокоптеров DJI сохранили в публичном репозитории GitHub закрытый ключ SSL-сертификата компании и AES-ключи для шифрования прошивок. Все это добро хранилось совершенно открыто на протяжении 4-х лет.

**Утечка данных в DXC Technologies**

> Осень 2017 года – инженер IT-аутсорсера DXC Technologies загрузил ключи доступа к AWS в публичный репозиторий

---

Firebase например хранит ключи с помощью [configstore](https://www.npmjs.com/package/configstore) в `~/.config/configstore/firebase-tools.json`

Почему бы не сохранять `access_token` c помощью configstore, а для CI брать из env или аргументов командной строки?

А если хранить критическую информацию в vk-hosting-config.json, хорошо бы предупреждать пользователя, что файл не указан в .gitignore
