### ISSUE TITLE
Error: 5: User authorization failed: invalid session.

### ISSUE THREAD

**Issue by zavx0z** [VKCOM/vk-miniapps-deploy#10]
maczavx0z:mvk zavx0z$ sudo vk-miniapps-deployPassword:
✔ Would you like to deploy to VK Mini Apps hosting using these commands? … yes
Error: 5: User authorization failed: invalid session.
    at api (/usr/local/lib/node_modules/@vkontakte/vk-miniapps-deploy/index.js:100:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.run (/usr/local/lib/node_modules/@vkontakte/vk-miniapps-deploy/index.js:258:15)
    at async run (/usr/local/lib/node_modules/@vkontakte/vk-miniapps-deploy/bin/vk-miniapps-deploy:43:22)
TypeError: Cannot read property 'upload_url' of undefined
maczavx0z:mvk zavx0z$ 

ЛОГИ
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/12.11.1/bin/node',
1 verbose cli   '/usr/local/lib/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'deploy',
1 verbose cli   '--scripts-prepend-node-path=auto'
1 verbose cli ]
2 info using npm@6.13.1
3 info using node@v12.11.1
4 verbose run-script [ 'predeploy', 'deploy', 'postdeploy' ]
5 info lifecycle mvk@1.0.0~predeploy: mvk@1.0.0
6 info lifecycle mvk@1.0.0~deploy: mvk@1.0.0
7 verbose lifecycle mvk@1.0.0~deploy: unsafe-perm in lifecycle true
8 verbose lifecycle mvk@1.0.0~deploy: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Volumes/backup/mp/mvk/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle mvk@1.0.0~deploy: CWD: /Volumes/backup/mp/mvk
10 silly lifecycle mvk@1.0.0~deploy: Args: [ '-c', 'vk-miniapps-deploy' ]
11 silly lifecycle mvk@1.0.0~deploy: Returned: code: 1  signal: null
12 info lifecycle mvk@1.0.0~deploy: Failed to exec deploy script
13 verbose stack Error: mvk@1.0.0 deploy: `vk-miniapps-deploy`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid mvk@1.0.0
15 verbose cwd /Volumes/backup/mp/mvk
16 verbose Darwin 18.7.0
17 verbose argv "/usr/local/Cellar/node/12.11.1/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "run" "deploy" "--scripts-prepend-node-path=auto"
18 verbose node v12.11.1
19 verbose npm  v6.13.1
20 error code ELIFECYCLE
21 error errno 1
22 error mvk@1.0.0 deploy: `vk-miniapps-deploy`
22 error Exit status 1
23 error Failed at the mvk@1.0.0 deploy script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by kuhel** [comment]
rm ~/.config/configstore/@vkontakte/vk-miniapps-deploy.json
