### ISSUE TITLE
Ошибка при деплое

### ISSUE THREAD

**Issue by batFormat** [VKCOM/vk-miniapps-deploy#12]
При деплое получаю ошибку, в моем случае причина была в том, что в бандле был файл лицензий в формате `txt`.

Я полагаю это происходит из-за того, что в библиотеке `terser-webpack-plugin` изменили поведение по умолчанию.
https://github.com/webpack-contrib/terser-webpack-plugin/pull/210

```
Upload error: {
  error: 'ERR_UNKNOWN: save bundle result "0"docs_upload_arch_fail',
  bwact: 'app_bundle',
  server: 815023,
  _sig: 'd4e8d352ac9546485f0964e37adf191d'
}
```

**Comment by ckorikov** [comment]
Подтверждаю, без файла лицензии работает.

**Comment by mahnunchik** [comment]
Аналогичная ошибка `error: 'ERR_UNKNOWN: save bundle result "0"docs_upload_arch_fail',`

@ckorikov а как без фала лицензии загрузить?

**Comment by mahnunchik** [comment]
Аналогичная проблема https://github.com/VKCOM/vk-miniapps-deploy/issues/3

**Comment by ckorikov** [comment]
@mahnunchik без файла загрузилось без проблем. Файл был txt.

**Comment by xpyctumo** [comment]
Перед деплоем начал появляться файл лицензии `LICENSE.txt`.

Соответственно, перед деплоем этот файл нужно удалять.
```bash
rm build/statiс/js/LICENSE.txt
```

Вынести это временное решение можно также и в файл `package.json`
```
"scripts": {
    "deploy": "react-scripts build && rm build/static/js/LICENSE.txt && vk-miniapps-deploy",
    ...
}
```

Тогда будет достаточно `yarn deploy` или `npm run-script deploy`

**Comment by mahnunchik** [comment]
С префиксами вот так: `"deploy": "rm -f build/static/js/*.LICENSE.txt && vk-miniapps-deploy"`
