### ISSUE TITLE
Deploy failed, error code: #108

### ISSUE THREAD

**Issue by mazda22x** [VKCOM/vk-miniapps-deploy#25]
Добрый день! Деплоил сегодня без проблем, потом в какой-то момент все деплои начали валиться с этой ошибкой.

> Deploy failed, error code: #108 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myapp@1.0.0 deploy: `vk-miniapps-deploy`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the myapp@1.0.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/a18700855/.npm/_logs/2020-09-27T10_20_40_871Z-debug.log
The terminal process "/bin/zsh '-c', 'npm run deploy'" terminated with exit code: 1.

 В логе есть такая инфа:

> 11 info lifecycle myapp@1.0.0-deploy: myapp@1.0.0
12 verbose lifecycle myapp@1.0.0-deploy: unsafe-perm in lifecycle true
13 verbose lifecycle myapp@1.0.0-deploy: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/a18700855/stands/ImageStylization/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/ApacheMaven3.6/bin
14 verbose lifecycle myapp@1.0.0-deploy: CWD: /Users/a18700855/stands/ImageStylization
15 silly lifecycle myapp@1.0.0-deploy: Args: [ '-c', 'vk-miniapps-deploy' ]
16 silly lifecycle myapp@1.0.0-deploy: Returned: code: 1  signal: null
17 info lifecycle myapp@1.0.0-deploy: Failed to exec deploy script
18 verbose stack Error: myapp@1.0.0 deploy: `vk-miniapps-deploy`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
18 verbose stack     at EventEmitter.emit (events.js:314:20)
18 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
18 verbose stack     at ChildProcess.emit (events.js:314:20)
18 verbose stack     at maybeClose (internal/child_process.js:1047:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
19 verbose pkgid myapp@1.0.0
20 verbose cwd /Users/a18700855/stands/ImageStylization
21 verbose Darwin 19.6.0
22 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "deploy"
23 verbose node v14.9.0
24 verbose npm  v6.14.8

**Comment by ilyapishchulin** [comment]
Актуально?

**Comment by ilyapishchulin** [comment]
Видимо нет

**Comment by AlexandrFiner** [comment]
Аналогичная проблема

**Comment by falconsapsan** [comment]
Тоже поймал Deploy failed, error code: #108.  - в какую сторону копать, чтобы пофиксить ошибку?

**Comment by falconsapsan** [comment]
> Тоже поймал Deploy failed, error code: #108. - в какую сторону копать, чтобы пофиксить ошибку?
Само прошло
