### ISSUE TITLE
Название приложения, которое мы деплоим в личке с "Администрация VK"

### ISSUE THREAD

**Issue by ub1x** [VKCOM/vk-miniapps-deploy#27]
На данный момент в личку приходит "Подтвердите изменение адреса Вашего приложения.
Код:"

Было бы круто добавить туда ещё и название приложения, к примеру:

"Подтвердите изменение адреса Вашего приложения "Домосед".
Код: "

**Comment by ub1x** [comment]
Да и в пуше на телефоне было бы неплохо такое реализовать.

**Comment by ilyapishchulin** [comment]
Сделаем, спасибо

**Comment by ilyapishchulin** [comment]
Сделали
