### ISSUE TITLE
Call process.exit() from noprompt mode

### ISSUE THREAD

**Issue by dev-plvlml** [VKCOM/vk-miniapps-deploy#38]
Hi everyone,
Is there a reason not to return exit status from noprompt mode? It could eliminate some difficulties with running vk-miniapps-deploy from a script.

https://github.com/VKCOM/vk-miniapps-deploy/blob/961147628e6b84f992430e6f79ff68fcd1899b57/bin/vk-miniapps-deploy#L29-L31

**Comment by ilyapishchulin** [comment]
Thank you for issue. Fixed
